version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - AI_SERVICE_URL=http://ai-service:5000
    depends_on:
      - ai-service

  ai-service:
    build:
      context: ./ai-services
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./ai-services:/app
      - /app/venv
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}

  # Optional: Add a local PostgreSQL instance for development
  # db:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=honeybee_dev
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 