name: honeybee
description: A new Flutter project
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  http: ^1.1.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 